version: '3.8'

services:
  echoo-backend:
    build: .
    container_name: echoo-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./uploads:/app/uploads
      - ./videos:/app/videos
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Redis用于缓存
  # redis:
  #   image: redis:alpine
  #   container_name: echoo-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped 